name: FunkyUHC
version: '${project.version}'
main: co.com.okaeri.funkyuhc.FunkyUHC
api-version: 1.18
authors: [ FunkyoAlejandra, Eltiodunsparce ]
description: Plugin para el evento UHC de funkyo
website: https://linktr.ee/FunkyoEnma

commands:
  mapSize:
    description: Cambiar el tamaño del mapa
    usage: mapSize <value>

  timeBar:
    description: Comandos con la barra de boss

  teams:
    description: Comandos referentes a los teams

  regeneration:
    description: Comandos referentes a la regeneración

  uhc:
    description: Comando principal del uhc

  score:
    description: Comando de scoreboard

  global:
    description: Enviar un chat a todos los equipos
    aliases:
      - g
      - G
      - GLOBAL